name: Calculatrice

# Déclenche si push sur la branche master
on:
  push:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Cloner mon projet sur le système ubuntu
      - uses: actions/checkout@v3

      - name: Installation de python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Installation des dépendances
        run: |
          pip install -r requirements.txt

      - name: Exécution des tests
        run: |
          pytest test.py
